Repository Carapacik/swagger_parser, pull requests merged in 2023-05, with the labels that each got.

#37 0.10.2 default values now generates in constructor
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/generator/rest_clients_test.dart
  swagger_parser_pages/lib/content/generator_content.dart
Labels: bug, enhancement

#38 0.10.3 $ref not being used and referenced if type is also defined
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
Labels: bug

#40 1.0
  .github/workflows/tests.yml
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/pubspec.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/programming_lang.dart
  swagger_parser/lib/src/generator/models/universal_component_class.dart
  swagger_parser/lib/src/generator/models/universal_data_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_interface_template.dart
  swagger_parser/lib/src/generator/templates/dart_typedef_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/type_utils.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/generator/rest_clients_test.dart
  swagger_parser/test/generator/root_interface_test.dart
  swagger_parser_pages/lib/content/main_page.dart
  swagger_parser_pages/pubspec.yaml
Labels: enhancement

#42 1.0.0+1 Topics
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/pubspec.yaml
  swagger_parser_pages/lib/content/generator_content.dart
Labels: enhancement
