Repository Carapacik/swagger_parser, pull requests merged in 2023-09, with the labels that each got.

#73 Fix error with replacement rules in allOf
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
Labels: bug

#75 Fix error with unnamed classes uniques names
  swagger_parser/CHANGELOG.md
  swagger_parser/analysis_options.yaml
  swagger_parser/lib/src/generator/models/all_of.dart
  swagger_parser/lib/src/generator/models/universal_component_class.dart
  swagger_parser/lib/src/generator/models/universal_data_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/models/universal_request_type.dart
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
Labels: bug

#81 1.4.0 Add support for common parameters for various paths
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
Labels: enhancement

#82 Requires Dart 3.0 or later
  .github/workflows/tests.yml
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/lib/src/config/config_exception.dart
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/generator_exception.dart
  swagger_parser/lib/src/generator/models/all_of.dart
  swagger_parser/lib/src/generator/models/generated_file.dart
  swagger_parser/lib/src/generator/models/programming_lang.dart
  swagger_parser/lib/src/generator/models/replacement_rule.dart
  swagger_parser/lib/src/generator/models/universal_component_class.dart
  swagger_parser/lib/src/generator/models/universal_data_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/models/universal_request_type.dart
  swagger_parser/lib/src/generator/models/universal_rest_client.dart
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_typedef_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/parser/parser_exception.dart
  swagger_parser/lib/src/utils/case_utils.dart
  swagger_parser/lib/src/utils/type_utils.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/lib/swagger_parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser_pages/lib/content/generator_content.dart
  swagger_parser_pages/pubspec.yaml
Labels: documentation, enhancement, dependencies

#85 Fix groupping words for acronyms and abbreviations
  swagger_parser/lib/src/utils/case_utils.dart
Labels: enhancement

#88 Code docs
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/open_api_info.dart
  swagger_parser/lib/src/generator/models/programming_lang.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_interface_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/pubspec.yaml
Labels: documentation

#89 Fixes for replacement rules and case utils
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/generator/models/replacement_rule.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/case_utils.dart
  swagger_parser/pubspec.yaml
Labels: bug
