Repository Carapacik/swagger_parser, pull requests merged in 2023-10, with the labels that each got.

#90 1.7.0 Flag 'mark_files_as_generated' and refactoring
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/programming_lang.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_interface_template.dart
  swagger_parser/lib/src/generator/templates/dart_typedef_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/generator/rest_clients_test.dart
  swagger_parser_pages/lib/content/generator_content.dart
  swagger_parser_pages/lib/content/information_box.dart
  swagger_parser_pages/lib/utils/file_utils.dart
  swagger_parser_pages/pubspec.yaml
Labels: enhancement

#96 Parser tests
  swagger_parser/lib/src/generator/models/universal_rest_client.dart
  swagger_parser/test/parser/data_classses_test.dart
  swagger_parser/test/parser/requests_test.dart
  swagger_parser/test/parser/schemas/basic_requests.2.0.json
  swagger_parser/test/parser/schemas/basic_requests.3.0.json
  swagger_parser/test/parser/schemas/basic_types_class.2.0.json
  swagger_parser/test/parser/schemas/basic_types_class.3.0.json
  swagger_parser/test/parser/schemas/empty_class.2.0.json
  swagger_parser/test/parser/schemas/empty_class.3.0.json
  swagger_parser/test/parser/schemas/reference_types_class.2.0.json
  swagger_parser/test/parser/schemas/reference_types_class.3.0.json
Labels: documentation, enhancement

#97 Multiple schemas support
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/bin/generate.dart
  swagger_parser/example/pubspec.yaml
  swagger_parser/example/schemas/openapi.json
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/programming_language.dart
  swagger_parser/lib/src/generator/models/universal_component_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_typedef_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/lib/swagger_parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/generator/rest_clients_test.dart
  swagger_parser/test/generator/root_client_test.dart
  swagger_parser/test/parser/data_classses_test.dart
  swagger_parser/test/parser/requests_test.dart
  swagger_parser/test/parser/schemas/of_like_class.3.1.json
  swagger_parser_pages/lib/content/generator_content.dart
  swagger_parser_pages/lib/content/information_box.dart
Labels: enhancement

#100 Cli info
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/bin/generate.dart
  swagger_parser/bin/swagger_parser.dart
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/generation_statistics.dart
  swagger_parser/lib/src/generator/models/universal_component_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/models/universal_request_type.dart
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/pubspec.yaml
Labels: enhancement

#102 Protect name
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/generator/models/universal_data_class.dart
  swagger_parser/lib/src/generator/models/universal_enum_class.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/dart_root_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/case_utils.dart
  swagger_parser/lib/src/utils/type_utils.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/parser/data_classses_test.dart
Labels: bug, enhancement

#116 Add an option for generating http response
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
Labels: enhancement

#125 1.10.6 non-object-additionalProperties
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/parser/data_classses_test.dart
  swagger_parser/test/parser/schemas/additional_properties_class.3.0.json
Labels: bug

#126 Unknown enum value
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/programming_language.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
  swagger_parser/lib/src/utils/type_utils.dart
  swagger_parser/test/generator/data_classes_test.dart
Labels: bug, enhancement

#109 Handling content types
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/programming_language.dart
  swagger_parser/lib/src/generator/models/universal_request.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/rest_clients_test.dart
  swagger_parser/test/parser/requests_test.dart
  swagger_parser/test/parser/schemas/basic_types_class.3.0.json
  swagger_parser/test/parser/schemas/of_like_class.3.1.json
  swagger_parser/test/parser/schemas/reference_types_class.3.0.json
Labels: enhancement
