Repository Carapacik/swagger_parser, pull requests merged in 2023-12, with the labels that each got.

#141 Add support for an another json serializer called `dart_mappable`
  README.md
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/.gitignore
  swagger_parser/example/build.yaml
  swagger_parser/example/pubspec.yaml
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/fill_controller.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/generator/models/json_serializer.dart
  swagger_parser/lib/src/generator/models/programming_language.dart
  swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_import_dto_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/data_classes_test.dart
  swagger_parser/test/parser/data_classses_test.dart
  swagger_parser/test/parser/schemas/enum_class.json
Labels: enhancement

#146 Upgrade 'dart:io' import logic
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
Labels: bug, enhancement, question

#148 fix: Path-level parameters no longer cause crash.
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
Labels: bug
