Repository Carapacik/swagger_parser, pull requests merged in 2024-01, with the labels that each got.

#151 Ignore prefer_schema_source for extract_schemas_from_url
  swagger_parser/bin/extract_schemas_from_url.dart
  swagger_parser/lib/src/generator/generator.dart
Labels: bug, enhancement

#152 Skip parameters and Remove tag special characters
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/lib/src/config/yaml_config.dart
  swagger_parser/lib/src/generator/generator.dart
  swagger_parser/lib/src/parser/parser.dart
Labels: enhancement

#153 Fix/map additional properties ref
  swagger_parser/CHANGELOG.md
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/parser/data_classes_test.dart
  swagger_parser/test/parser/schemas/additional_properties_class.2.0.json
Labels: bug

#155 Fix multipart requests generation
  .gitignore
  swagger_parser/.gitignore
  swagger_parser/README.md
  swagger_parser/example/.gitignore
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/generator/models/universal_type.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/parser/parser.dart
  swagger_parser/lib/src/utils/type_utils.dart
  swagger_parser/lib/src/utils/utils.dart
  swagger_parser/test/generator/rest_clients_test.dart
Labels: bug
