Repository Carapacik/swagger_parser, pull requests merged in 2024-03, with the labels that each got.

#184 Multi Fix
  swagger_parser/lib/src/parser/model/universal_request_type.dart
  swagger_parser/lib/src/parser/parser/open_api_parser.dart
  swagger_parser/lib/src/utils/output/io_output.dart
Labels: bug

#198 Multifix
  swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
  swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
  swagger_parser/lib/src/parser/parser/open_api_parser.dart
  swagger_parser/lib/src/parser/utils/type_utils.dart
Labels: bug, enhancement

#209 #208 - Support dart retrofit 4.1.0 @Extras parameter option
  swagger_parser/CHANGELOG.md
  swagger_parser/README.md
  swagger_parser/example/swagger_parser.yaml
  swagger_parser/lib/src/config/swp_config.dart
  swagger_parser/lib/src/generator/config/generator_config.dart
  swagger_parser/lib/src/generator/generator/fill_controller.dart
  swagger_parser/lib/src/generator/model/programming_language.dart
  swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
  swagger_parser/lib/src/parser/model/universal_request_type.dart
  swagger_parser/pubspec.yaml
  swagger_parser/test/generator/rest_clients_test.dart
Labels: enhancement

#215 Quality improvements
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: enhancement

#219 Add MappableField
  swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart
  swagger_parser/test/generator/data_classes_test.dart
Labels: enhancement
